# Generated by Django 4.1.3 on 2022-11-01 14:49

import agenzia_immobiliare.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenziaImmobiliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ragione_sociale', models.CharField(max_length=100)),
                ('nome_agenzia', models.CharField(max_length=100)),
                ('partita_iva', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to=agenzia_immobiliare.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='PermessiAgenteAgenzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permesso', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('agente_imobiliare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agenzia_immobiliare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenzia_immobiliare.agenziaimmobiliare')),
            ],
        ),
    ]
