# Generated by Django 4.1.3 on 2022-11-01 14:49

import annuncio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indirizzo', '0001_initial'),
        ('agenzia_immobiliare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrattoImmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FotoImmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=annuncio.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='TipologiaImmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Annuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superficie', models.IntegerField()),
                ('numero_vani', models.IntegerField()),
                ('numero_bagni', models.IntegerField()),
                ('numero_camere', models.IntegerField()),
                ('numero_piani', models.IntegerField()),
                ('piano', models.IntegerField()),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('agenzia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenzia_immobiliare.agenziaimmobiliare')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annuncio.contrattoimmobile')),
                ('foto', models.ManyToManyField(to='annuncio.fotoimmobile')),
                ('indirizzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indirizzo.indirizzo')),
                ('tipologie', models.ManyToManyField(to='annuncio.tipologiaimmobile')),
            ],
        ),
    ]
